groups:
- name: erini-cd
  jobs:
  - deploy-cube-release
- name: erini-ci
  jobs:
  - run-unit-tests

jobs:
- name: run-unit-tests
  plan:
  - get: eirini
  - get: ci-resources
  - task: run-tests
    file: ci-resources/tasks/run-unit-tests.yml

- name: deploy-cube-release
  plan:
  - get: eirini-sl-director
  - get: ci-resources
  - get: eirini-release
    trigger: true
  - get: cf-deployment
    trigger: true
  - get: bosh-lite-softlayer
  - task: deploy
    privileged: true
    params:
      BOSH_DIRECTOR: ((bosh_director))
      DIRECTOR_IP: ((director_ip))
      DIRECTOR_NAME: ((director_name))
      CC_API: ((cc_api))
      KUBE_CONF: ((kube_conf))
      KUBE_ENDPOINT: ((kube_endpoint))
      KUBE_NAMESPACE: ((kube_namespace))
      NATS_IP: ((nats_ip))
      NATS_PASSWORD: ((nats_password))
      SYSTEM_DOMAIN: ((system_domain))
      EIRINI_IP: ((eirini_ip))
      EIRINI_ADDRESS: ((eirini_address))
    file: ci-resources/tasks/deploy-cube-release.yml

resources:
- name: eirini
  type: git
  source:
    uri: https://github.com/julz/cube.git
    branch: master

- name: ci-resources
  type: git
  source:
    uri: https://github.com/JulzDiverse/cube-release-ci.git
    branch: wip-update-release

- name: eirini-release
  type: git
  source:
    uri: https://github.com/andrew-edgar/cube-release.git
    branch: develop

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    branch: ((cf-deployment-version))

- name: bosh-lite-softlayer
  type: git
  source:
    uri: http://github.com/JulzDiverse/bosh-lite-softlayer.git
    branch: master

- name: eirini-sl-director
  type: git
  source:
    uri: ((director_repo))
    branch: master
    private_key: ((eirini-sl-director-private-key))
