---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: diegoteam/eirini

inputs:
- name: state
- name: ci-resources

run:
  path: ci-resources/tasks/delete-cf-deployment.sh
