---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: diegoteam/eirini

params:
  BOSH2_ENV_ALIAS: lite

inputs:
- name: ci-resources
- name: state

outputs:
- name: out

run:
  path: ci-resources/tasks/upload-stemcell.sh
