groups:
- name: erini-cd
  jobs:
  - deploy-eirini-release
- name: manage-cf
  jobs:
  - delete-cf-deployment
- name: manage-director
  jobs: []

jobs:
- name: deploy-eirini-release
  plan:
  - get: state
    passed: []
    trigger: false
  - get: ci-resources
  - get: eirini-release
    trigger: true
  - get: cf-deployment
    trigger: true
  - get: bosh-lite-softlayer
  - task: deploy
    privileged: true
    params:
      BOSH_DIRECTOR: ((bosh_director))
      DIRECTOR_NAME: ((bosh_lite_name))
      CC_API: ((cc_api))
      KUBE_CONF: ((kube_conf))
      KUBE_ENDPOINT: ((kube_endpoint))
      KUBE_NAMESPACE: ((kube_namespace))
      NATS_IP: ((nats_ip))
      SYSTEM_DOMAIN: ((system_domain))
      EIRINI_IP: ((eirini_ip))
      EIRINI_ADDRESS: ((eirini_address))
      REGISTRY_ADDRESS: ((registry_address))
    file: ci-resources/tasks/deploy-cube-release.yml

- name: delete-cf-deployment
  plan:
  - get: ci-resources
  - get: state
  - task: delete
    params:
      DIRECTOR_NAME: ((bosh_lite_name))
    file: ci-resources/tasks/delete-cf-deployment.yml

resources:
- name: ci-resources
  type: git
  source:
    uri: https://github.com/JulzDiverse/cube-release-ci.git
    branch: wip-update-release

- name: eirini-release
  type: git
  source:
    uri: https://github.com/andrew-edgar/cube-release.git
    branch: develop

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    branch: ((cf-deployment-version))

- name: bosh-lite-softlayer
  type: git
  source:
    uri: http://github.com/JulzDiverse/bosh-lite-softlayer.git
    branch: master

- name: state
  type: git
  source:
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: master
    private_key: ((github-private-key))
