groups:
- name: erini-cd
  jobs:
  - deploy-cube-release
- name: erini-ci
  jobs:
  - run-unit-tests
- name: manage-cf
  jobs:
  - delete-cf-deployment

jobs:
- name: run-unit-tests
  plan:
  - get: eirini
  - get: ci-resources
  - task: run-tests
    file: ci-resources/tasks/run-unit-tests.yml

resources:
- name: eirini
  type: git
  source:
    uri: https://github.com/julz/cube.git
    branch: master
